name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        cache: true

    - name: Format
      run: go fmt ./...

    - name: Vet
      run: go vet ./...

    - name: Build
      run: go build ./...

    - name: Test
      run: go test -short ./...
